package com.ddd.backend.websocket.dto;

public enum AutomationUiEventType {
    STATE,
    GUIDE,
    TARGET,
    TARGET_CLEAR,
    DECISION_REQUIRED,
    DECISION_RESOLVED,
    DECISION_CLEAR,
    SECURE_INPUT_REQUIRED,
    SECURE_INPUT_RESOLVED,
    SECURE_INPUT_CLEAR,
    CONFIRMATION_REQUIRED,
    CONFIRMATION_RESOLVED,
    CONFIRMATION_REJECTED,
    CONFIRMATION_CLEAR
}
