import type {
  GenerateTextInput,
  GenerateTextResult,
} from "./ai.service.js";

import {
  createNextActionPrompt,
} from "../prompts/nextActionPrompt.js";

import {
  bindTrustedRequestId,
  parseStructuredAIResponse,
} from "../output/aiResponse.parser.js";

import {
  createStructuredFallbackResponse,
} from "../output/aiResponse.fallback.js";

import {
  adaptBackendDomToModelInput,
} from "../api/domRequest.adapter.js";

import type {
  AiActionRequest,
} from "../api/aiRequest.types.js";

import type {
  StructuredAIResponse,
} from "../output/aiResponse.types.js";

import {
  enforceUserDecisionPolicy,
} from "../policy/userDecision.policy.js";

import {
  createSecureInputPauseForRequest,
  enforceSecureInputPolicy,
} from "../secureInput/secureInput.policy.js";

import {
  classifyDepositScenarioStage,
  enforceDepositScenarioPolicy,
  finalizeDepositScenarioGuidance,
} from "../deposit/depositScenario.policy.js";

import {
  createDepositFinalBoundaryResponse,
  enforceDepositFinalConfirmationPolicy,
} from "../deposit/depositFinalConfirmation.policy.js";

export type StructuredActionTextGenerator = (
  input: GenerateTextInput,
) => Promise<GenerateTextResult>;

async function generateProductionText(
  input: GenerateTextInput,
): Promise<GenerateTextResult> {
  const { aiService } =
    await import("./ai.service.js");

  return aiService.generateText(input);
}

export async function generateStructuredAction(
  request: AiActionRequest,
  generateText: StructuredActionTextGenerator =
    generateProductionText,
): Promise<StructuredAIResponse> {
  /*
   * D26 fail-closed boundary: resolve a sanitized SECURE_INPUT element before
   * prompt construction or a model call. Backend owns the secure channel;
   * neither its raw value nor channel identifiers enter C's model context.
   */
  const securePause =
    createSecureInputPauseForRequest(request);

  if (securePause) {
    return securePause;
  }

  /*
   * D27 deterministic boundary: the current sanitized final target and Demo
   * completion screen are resolved before prompt construction. This prevents
   * the model from choosing a final target or manufacturing confirmation
   * authority. Secure input remains the earlier, higher-priority boundary.
   */
  const finalBoundary =
    createDepositFinalBoundaryResponse(request);

  if (finalBoundary) {
    return finalBoundary;
  }

  const dom = adaptBackendDomToModelInput(
    request.domSnapshot,
  );

  const prompt = createNextActionPrompt(
    request.requestId,
    request.userGoal,
    dom,
    request.userDecisionContext,
  );

  const result = await generateText({
    prompt,
  });

  if (result.source === "FALLBACK") {
    const fallback = createStructuredFallbackResponse(
      request.requestId,
    );

    return classifyDepositScenarioStage(request) ===
      "SECURE_INPUT"
      ? enforceDepositScenarioPolicy(
          fallback,
          request,
        )
      : fallback;
  }

  try {
    const parsed =
      parseStructuredAIResponse(result.text);

    /*
     * requestId is generated by C before the prompt is built. The model's
     * echoed value is untrusted and must not replace that correlation ID.
     */
    const structured =
      bindTrustedRequestId(
        parsed,
        request.requestId,
      );

    const secureChecked =
      enforceSecureInputPolicy(
        structured,
        request,
      );

    const depositStage =
      classifyDepositScenarioStage(request);

    const depositChecked =
      enforceDepositScenarioPolicy(
        secureChecked,
        request,
      );

    const finalChecked =
      enforceDepositFinalConfirmationPolicy(
        depositChecked,
        request,
      );

    const policyChecked =
      enforceUserDecisionPolicy(
        finalChecked,
        request,
      );

    /*
     * D24 remains authoritative for decision option membership and labels.
     * Its generic wait message must not erase D25's stage-specific, static
     * guidance after those checks have succeeded.
     */
    const guided =
      finalizeDepositScenarioGuidance(
        policyChecked,
        depositChecked,
        depositStage,
      );

    validateTargetElementId(
      guided,
      request,
    );

    return guided;
  } catch {
    console.error(
      "[AI Engine] Structured response validation failed. Fallback is returned.",
    );

    return createStructuredFallbackResponse(
      request.requestId,
    );
  }
}

function validateTargetElementId(
  response: StructuredAIResponse,
  request: AiActionRequest,
): void {
  if (!response.targetElementId) {
    return;
  }

  const exists =
    request.domSnapshot.elements.some(
      (element) =>
        element.elementId ===
        response.targetElementId,
    );

  if (!exists) {
    throw new Error(
      `[AI Engine] 존재하지 않는 targetElementId입니다: ${response.targetElementId}`,
    );
  }
}
